### ISSUE TITLE
Bug: 0.8.1 is missing courier.toml

### ISSUE THREAD

**Issue by subenji** [alwaysintreble/TheMessengerRandomizerModAP#1]
### What happened?

Between myself setting up the Messenger AP randomiser and a friend doing so, you published 0.8.1. He reported that after installing the mod, the randomiser options were not present in Third Party Mod Options.

After some investigation, I saw in `The Messenger\log.txt ` that it reported `Located 0 mods containing a courier.toml`, and the issue was resolved by installing 0.8.0 and then 0.8.1 on top.

### What were the expected results?

.

### Is this reproducible?

Attempt to install the mod fresh using only the 0.8.1 release.

**Comment by alwaysintreble** [comment]
0.8.1 was also missing the randomizer dll. I think my release script failed somewhere but it's fixed now. Also I apparently didn't get a notification for this so that's fixed now too 😓 Thanks for the reports! 😄
