### ISSUE TITLE
Bug: Reset Randomizer File Slots not showing. Group run in 38 hours. 

### ISSUE THREAD

**Issue by KrimzonKhaos** [alwaysintreble/TheMessengerRandomizerModAP#14]
### What happened?

Tried reinstalling Courier, running Mini Installer again, tried the zip and the extracted files in the mod folder for 0.13.0 alpha 4 and 3 and it's still not showing. Backed up, renamed save, removed. 
![image](https://github.com/alwaysintreble/TheMessengerRandomizerModAP/assets/158540686/04807509-0ab6-45fd-b757-82f82f842b99)
![image-1](https://github.com/alwaysintreble/TheMessengerRandomizerModAP/assets/158540686/28a27a18-f522-4160-90c3-230de8369120)

### What were the expected results?

To show option to Reset Randomizer File Slots. 

### Is this reproducible?

Yes. Tried 4 times now with different configurations.

**Comment by KrimzonKhaos** [comment]
![image-2](https://github.com/alwaysintreble/TheMessengerRandomizerModAP/assets/158540686/6fd13eab-f101-4923-a702-09c10f537321)
![image-3](https://github.com/alwaysintreble/TheMessengerRandomizerModAP/assets/158540686/d2a17ce0-90f6-4ccb-9727-c8e17a9b2c19)

**Comment by KrimzonKhaos** [comment]
Tried Courier 7.0 and 7.1.
Tried zip, extracted, and folder inside extracted and unextracted for Courier and 13.0 alpha 4

**Comment by alwaysintreble** [comment]
You downloaded one of the newer testing builds. While it should still be stable it's not guaranteed, but it has many new features including the removal of that menu. Steps of how to play with it now are here for now https://github.com/alwaysintreble/TheMessengerRandomizerModAP/releases/tag/v0.13.0-alpha

**Comment by KrimzonKhaos** [comment]
Thank you, that makes sense. Most of the instructions for these are download the latest, but this being an alpha makes sense. I appreciate the fast reply and the fix, I'll try that out later. You have a wonderful rest of your day/night!
