### ISSUE TITLE
Option to enable/disable displaying the items in shop

### ISSUE THREAD

**Issue by theStoRmsN** [alwaysintreble/TheMessengerRandomizerModAP#18]
### What should this feature do?

Is it possible to get a setting that enables/disables displaying the items in the shop?
Especially in a race scenario this is kind of a bummer, because it leads to only shard grinding, if all keys are in the shop. 

Probably the logic should also be altered that not all 6 keys can appear in the shop at al

**Comment by alwaysintreble** [comment]
https://github.com/alwaysintreble/TheMessengerRandomizerModAP/commit/7f8a6479262d98f9191e4549031b7891342fb726
and
https://github.com/alwaysintreble/TheMessengerRandomizerModAP/commit/0f36694a61877d0f36ab875982a0f31443f89b15
